# -*- coding: utf-8 -*-
"""Bitcoin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q5m28ekdkELiyjhDrsvGvITIuPk0OTxQ
"""

import pandas as pd
import numpy as np
# from google.colab import drive
# drive.mount('/content/drive')
import matplotlib.pyplot as plt

df= pd.read_csv('bitcoin.csv')
df

date= df['Date']

df1= df[::-1]
df1

from datetime import datetime
def days(d1,d2):
  date_format = "%b %d, %Y"
  a = datetime.strptime(d1, date_format)
  b = datetime.strptime(d2, date_format)
  delta = b - a
  return delta.days

print(days('Apr 30, 2013','Jul 31, 2017'))

d1= 	'Jul 31, 2017'

d2= 'Aug 2, 2017'

num = days(d1,d2)

if(num>0):
  df['open_pred']= df[['Open']].shift(num)

df

df= df.dropna()
df

X= df['Open'].to_numpy().reshape(-1, 1)
Y= df['open_pred'].to_numpy()

from sklearn.model_selection import train_test_split as tts
x_train, x_test, y_train, y_test= tts(X,Y, test_size=0.2)

from sklearn.svm import SVR 
svr_rbf= SVR(kernel='rbf',C=1e3, gamma=0.00001)
svr_rbf.fit(x_train,y_train)

y_pred=svr_rbf.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error

print(mean_absolute_percentage_error(y_pred,y_test))

print(svr_rbf.predict(np.array(2763.24).reshape(-1, 1)))

ope= svr_rbf.predict(np.array(2763.24).reshape(-1, 1))

if num<0:
  print(df['Open'][-num])
elif num>1500:
  print("duration limit exceeded")
else:
  print(ope)